myconfig.myconfig_admin_settings_form:
  path: '/admin/config/mysite/configuration'
  defaults:
    _form: '\Drupal\myconfig\Form\ConfigurationForm'
    _title: 'ConfigurationForm'
  requirements:
    _permission: 'administer site configuration'
  options:
    _admin_route: TRUE
system.admin_config_myconfig:
  path: '/admin/config/mysite'
  defaults:
    _controller: '\Drupal\system\Controller\SystemController::systemAdminMenuBlockPage'
    _title: 'Mysite'
  requirements:
    _permission: 'administer site configuration'